apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app.k8s/name: vault
  template:
    metadata:
      labels:
        app.k8s/name: vault
    spec:
      containers:
        - name: vault
          image: vault:1.13.3
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  type: NodePort
  ports:
    - port: 8200
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.k8s/name: vault